const LOCATION_REFRESH = "LOCATION_REFRESH";
const LOCATION_RESET = "LOCATION_RESET";
const LOCATION_SET_USER = "LOCATION_SET_USER";
const LOCATION_ADD = "LOCATION_ADD";


export default {
  LOCATION_REFRESH,
  LOCATION_RESET,
  LOCATION_SET_USER,
  LOCATION_ADD,
};
