const REPORT_ADD = "REPORT_ADD";
const REPORT_END = "REPORT_END";
const REPORT_DELETE = "REPORT_DELETE";
const REPORT_RESET = "REPORT_RESET";

export default {
  REPORT_ADD,
  REPORT_END,
  REPORT_DELETE,
  REPORT_RESET,
};
